# **Week 9 Day 1**

## Basics of numpy


In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1,2,3],[4,5,6]])
print("1D array:", arr1)
print("2D array:\n", arr2)


1D array: [1 2 3 4]
2D array:
 [[1 2 3]
 [4 5 6]]


In [4]:
print("Shape of arr2:", arr2.shape)
print("Number of dimensions:", arr2.ndim)

Shape of arr2: (2, 3)
Number of dimensions: 2


In [5]:
print("Datatype:", arr2.dtype)
print("Size:", arr2.size)

Datatype: int64
Size: 6


In [6]:
print("First element:", arr1[0])
print("Slice:", arr1[1:3])
print("2D indexing:", arr2[1,2])  # row 1, col 2

First element: 1
Slice: [2 3]
2D indexing: 6


In [7]:
print("Last element:", arr1[-1])

Last element: 4


In [8]:
arr3 = np.arange(1, 13)  # 1 to 12
arr3_reshaped = arr3.reshape(3,4)
print("Reshaped array:\n", arr3_reshaped)

Reshaped array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
print("Flattened:", arr3_reshaped.ravel())

Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Addition:", a+b)
print("Multiplication:", a*b)
print("Square:", a**2)

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Square: [1 4 9]


In [11]:
print("Square root:", np.sqrt(a))
print("Exponential:", np.exp(a))
print("Mean:", np.mean(a))

Square root: [1.         1.41421356 1.73205081]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Mean: 2.0


In [12]:
rand_arr = np.random.rand(3,3)  # 3x3 random numbers [0,1)
print(rand_arr)

rand_ints = np.random.randint(1,10,size=(2,4))  # integers 1-9
print(rand_ints)

[[0.48485053 0.56244836 0.94526707]
 [0.26040144 0.59614346 0.82350331]
 [0.39777018 0.08735112 0.59392685]]
[[4 5 8 7]
 [9 2 4 7]]


In [13]:
# Create array 1-10, reshape to 2x5, multiply by 2, print sum of columns
arr = np.arange(1,11).reshape(2,5)
arr = arr*2
print("Sum of columns:", arr.sum(axis=0))

Sum of columns: [14 18 22 26 30]


In [14]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])
print("Broadcasted addition:\n", a+b)

Broadcasted addition:
 [[2 4 6]
 [5 7 9]]
